# Alacritty Configuration

[env]
TERM = "alacritty"

[window]
opacity = 1.0
decorations = "full"
dynamic_padding = true

[window.padding]
x = 10
y = 10

[font]
size = 10

[font.normal]
family = "Noto Sans Mono"

[font.bold]
family = "Noto Sans Mono"

[font.italic]
family = "Noto Sans Mono"

[font.bold_italic]
family = "Noto Sans Mono"

# Base16 Darcula Colors
[colors.primary]
background = "0x2b2b2b"
foreground = "0xa9b7c6"

[colors.cursor]
text = "0x2b2b2b"
cursor = "0xa9b7c6"

[colors.normal]
black   = "0x2b2b2b"
red     = "0x4eade5"
green   = "0x6a8759"
yellow  = "0xbbb529"
blue    = "0x9876aa"
magenta = "0xcc7832"
cyan    = "0x629755"
white   = "0xa9b7c6"

[colors.bright]
black   = "0x606366"
red     = "0x4eade5"
green   = "0x6a8759"
yellow  = "0xbbb529"
blue    = "0x9876aa"
magenta = "0xcc7832"
cyan    = "0x629755"
white   = "0xffffff"

[[colors.indexed_colors]]
index = 16
color = "0x689757"

[[colors.indexed_colors]]
index = 17
color = "0x808080"

[[colors.indexed_colors]]
index = 18
color = "0x323232"

[[colors.indexed_colors]]
index = 19
color = "0x323232"

[[colors.indexed_colors]]
index = 20
color = "0xa4a3a3"

[[colors.indexed_colors]]
index = 21
color = "0xffc66d"

[selection]
save_to_clipboard = true

[terminal.shell]
program = "wsl.exe"
args = ["-d", "ArchLinux", "--cd", "~"]

[keyboard]
bindings = [
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Insert", mods = "Shift", action = "Paste" }
]

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Right"
mods = "Control"

[mouse.bindings.command]
program = "powershell.exe"
args = [
    "-NoProfile",
    "-STA",
    "-ExecutionPolicy", "Bypass",
    "-Command", "$p = Join-Path $env:APPDATA 'alacritty\\wpaste.ps1'; & $p"
]
